# setwd("../chessdoodles")
rm(list=ls())
load(".RData")

gameName<-"e122510018"
position<-setup(gameName,T)
pgnVec<-linesToPgn(readLines(list.files(pattern = "riso")))
args(newPosition)
for(pgn in pgnVec){position<-quickInput(sub("^\\d+","",pgn))}
write.csv(position,paste(gameName,"csv",sep="."))


position<-rbind(position,newPosition("C1600W_1.e3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_1...d5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_2.Qh5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_2...Nf6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_3.Qh4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_3...Qd6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_4.Nc3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_4...e5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_5.Nf3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_5...Nc6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_6.Bb5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_6...Bd7",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_7.b3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_7...Nb4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_8.Bd3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_8...Be7",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_9.Ba3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_9...Nxd3",nrow(position))); mobility2(nrow(position)-0) # "+" returns error
position<-rbind(position,newPosition("C1600W_10.cxd3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_10...Qxa3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_11.Nxe5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_11...Be6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_12.Nb5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_12...Qc5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_13.Qa4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_13...O-O",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_14.Ke2",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_14...Qb6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_15.Nc3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_15...Qd6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_16.Qd4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_16...c5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_17.Qf4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_17...Nh5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_18.Qa4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_18...Qxe5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_19.g4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_19...Nf6",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_20.h3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_20...d4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_21.f4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_21...Qb8",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_22.Ne4",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_22...b5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_23.Qa3",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_23...Qb7",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_24.Nxc5",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_24...Qg2",nrow(position))); mobility2(nrow(position)) # "+" returns error
position<-rbind(position,newPosition("C1600W_25.Kd1",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_25...Qxh1",nrow(position))); mobility2(nrow(position)) # "+" returns error
position<-rbind(position,newPosition("C1600W_26.Kc2",nrow(position))); mobility2(nrow(position))
position<-rbind(position,newPosition("C1600W_26...Qxa1",nrow(position))); mobility2(nrow(position))
gameName<-paste(Sys.Date(),"C1600W.csv")
fileName<-file.path("positions",gameName)
file.exists(fileName)
write.csv(position,fileName)

gameName<-"e121236870"
position<-setup(gameName,T)
pgnVec<-linesToPgn(readLines(list.files(pattern = "riso.+31.pgn")))
for(pgn in pgnVec){
  # print(sub("^\\d+","",pgn))
  position<-quickInput(sub("^\\d+","",pgn))
}
ifelse(20<nrow(position),
       print(position[seq(1,nrow(position),length.out = 20),seq(1,64,length.out = 10)]),
       print(position[,seq(1,64,length.out = 10)]))
write.csv(position,paste(gameName,"csv",sep="."))

plotPattern<-paste(gameName,".*\\.",sep="")

mobility<-data.frame(white=unlist(sapply(grep(plotPattern,row.names(position)), 
                                         mobility2)["white",]),
                     black=unlist(sapply(grep(plotPattern,row.names(position)), mobility2)["black",]),
                     row.names=row.names(position)[grep(plotPattern,row.names(position))])
plot(1:nrow(mobility),mobility$white,type="l",ylim=c(1,100), 
     col = "red",xlab = "moves",ylab = "mobility",main = gameName)
lines(mobility$black,type="l", col = "blue")

for(n in grep("empty",row.names(position))){
  abline(v=n-1, col="green")
}
# fileName<-file.path("chessdoodles","positions",paste(gameName,".csv",sep=""))
# fileName<-"positions/all.csv"
# file.exists(fileName)
# write.csv(position,fileName)

gameName<-"e120987680"
position<-setup(gameName)
position<-setup(gameName,T)
pgnVec<-linesToPgn(readLines(list.files(pattern = paste(gameName,"pgn",sep="."))))
for(pgn in pgnVec){
  # print(sub("^\\d+","",pgn))
  position<-quickInput(sub("^\\d+","",pgn))
}
ifelse(20<nrow(position),
       print(position[seq(1,nrow(position),length.out = 20),seq(1,64,length.out = 10)]),
       print(position[,seq(1,64,length.out = 10)]))
write.csv(position,paste(gameName,"csv",sep="."))

plotPattern<-paste(gameName,".*\\.",sep="")

mobility<-data.frame(white=unlist(sapply(grep(plotPattern,row.names(position)), 
                                         mobility2)["white",]),
                     black=unlist(sapply(grep(plotPattern,row.names(position)), mobility2)["black",]),
                     row.names=row.names(position)[grep(plotPattern,row.names(position))])
plot(1:nrow(mobility),mobility$white,type="l",ylim=c(1,100), 
     col = "red",xlab = "moves",ylab = "mobility",main = gameName)
lines(mobility$black,type="l", col = "blue")
legend(x="topright",legend=c("white","black"),fill = c("red","blue"))
plotPattern<-paste(gameName,".*\\.",sep="")

mobility<-data.frame(white=unlist(sapply(grep(plotPattern,row.names(position)), 
                                         mobility2)["white",]),
                     black=unlist(sapply(grep(plotPattern,row.names(position)), mobility2)["black",]),
                     row.names=row.names(position)[grep(plotPattern,row.names(position))])
plot(1:nrow(mobility),mobility$white,type="l",ylim=c(1,100), col = "red", 
     xlab = paste("game",gameName), ylab="mobility")
lines(mobility$black,type="l", col = "blue")
legend("topright",c("white","black"),fill = c("red","blue"))

for(n in grep("empty",row.names(position)[grep(gameName,row.names(position))])){
  abline(v=n-1, col="green")
}

gameName
fileName<-file.path("positions",paste(gameName,".csv",sep=""))
file.exists(fileName)
write.csv(position[grep(gameName,row.names(position)),],fileName)

position<-read.position("positions/all.csv")

position[seq(1,nrow(position),length.out=20),]

gameName<-"C1200W"

position<-setup(gameName)
board()
position<-quickInput(".e3")
sapply(nrow(position)-(1:0),mobility2)
position<-quickInput("...d5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qf3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...e5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Nc3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Nf6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".b3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Nc6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Bb5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qd6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Nge2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bd7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".O-O")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qe6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Bb2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Nb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rfc1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...c6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".a3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...cxb5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".axb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bxb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ba3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bxa3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxa3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...b4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ra5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...bxc3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Nxc3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...e4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qg3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...O-O")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rca1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...a6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qc7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Ra7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qc5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...b6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qd4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Rc8")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxa6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Rxa6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxa6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Rb8")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".h3")
sapply(nrow(position)-(2:0),mobility2,piecePattern=pawnPattern)
position<-quickInput("...h6")
sapply(nrow(position)-(2:0),mobility2, piecePattern=pawnPattern)
position<-quickInput(".Qb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kf1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg6")
sapply(nrow(position)-(2:0),mobility2,piecePattern=kingPattern)
position<-quickInput(".Ke2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kf5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".d3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qc6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kd2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qb7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ra1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Rc8")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".g4+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ne2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qc7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Nd4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qh2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qxb6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qxf2+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ne2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Rxc2+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kxc2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qxe2+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kc3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qxd3+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qd2+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ka3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qh2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Be6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rc1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qxh3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".b4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qg3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".b5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qf2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qd4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Nxg4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rc3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qg3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ka4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qe1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".b6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bd7+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kb4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Nxe3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qxe3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qf1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kc5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qb5+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kd6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bg4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rc6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Be6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kc7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qa5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kb8")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...h5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qg3+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qc7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qb5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".b7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...e3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Qb6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Qb6+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxb6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...e2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rb1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bf5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Re1")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...d4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxe2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...d3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd2")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Be4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rxd3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Bxb7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kxb7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...g5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd6+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kc7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...f5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kd7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kf7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kc6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...f4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kd5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...f3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Ke5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...g4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kf4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rf5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rf8")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rf5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kg3")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kh4")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kg6")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Rd6+")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...Kh7")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput(".Kxh5")
sapply(nrow(position)-(2:0),mobility2)
position<-quickInput("...f2")
sapply(nrow(position)-(2:0),mobility2)

